Iter13
Froctnow/shorturl pull request #12
Opened 2024-05-05 16:34 UTC by Froctnow

2024-05-19 19:40 UTC, Bazys requested changes
пра мелких вопросов.

2024-05-19 19:40 UTC, Bazys commented on internal/app/client/pg/queries/shortener.sql
> +SELECT events.publish($1, $2, $3, $4);
какое то очень интересное решение.
Может лучше посмотреть в сторону `sqlc` - какое никакое уже устоявшееся решение, и имеет много звезд на гитхабе.
Все равно мигратор используешь.

2024-05-19 19:40 UTC, Bazys commented on pkg/pgclient/adapter.go
> +func (l *LogAdapter) Log(ctx context.Context, level pgx.LogLevel, msg string, data map[string]interface{}) {
Параметр функции, названный `data`, не используется в теле функции. В Go, если определили параметр в функции, но не использовали его внутри, это считается неоптимальным стилем, поскольку параметр занимает место в сигнатуре функции и может сбивать с толку при чтении кода.
В данном случае, есть два возможных решения:
1. **Удаление параметра:** Если параметр `data` действительно не нужен для работы функции, его можно просто удалить из сигнатуры функции. Это делает код чище и проще для понимания.
2. **Переименование в `_`:** Если параметр не используется, но его наличие обязательно по какой-то причине (например, для соответствия интерфейсу или для использования в будущем), его можно переименовать в `_`. В Go, символ `_` используется для игнорирования переменной. Переменные, именованные как `_`, не обязаны быть использованы, т.е. не будет копирования неиспользуемого значения внутрь функции. Это позволяет сохранить сигнатуру функции неизменной, но явно указывает на то, что данный параметр в настоящее время не используется и избежать лишнего использования памяти.

2024-05-19 19:40 UTC, Bazys commented on internal/app/shortenerprovider/create_url.go
> +	URL string,
локально точно надо в верхнем регистре?

2024-05-19 19:40 UTC, Bazys commented on pkg/pgclient/client.go
> +	"context"
подключи `goimports` или даже `gofumpt` к проекту. На сохранение из среды или на гит-хук при коммите.

2024-05-25 04:03 UTC, Froctnow commented on internal/app/client/pg/queries/shortener.sql
> +SELECT events.publish($1, $2, $3, $4);
Ревью предыдущего шло слишком долго, и я уже продвинулся до пятого спринта, где проект большой. Не вижу смысла уходить на другое решение, это вполне себе production решение, мы используем его и все норм

2024-05-26 19:53 UTC, Bazys approved these changes
goimports все равно настоятельно рекомендую подключить

2024-08-10 12:38 UTC, closed without merging