iter15 Добавил ручку на удаление URL
Froctnow/shorturl pull request #15
Opened 2024-07-07 11:18 UTC by Froctnow

2024-07-07 19:12 UTC, Bazys requested changes
есть несколько вопросорв

2024-07-07 19:12 UTC, Bazys commented on internal/app/client/pg/queries/shortener.sql
> +WHERE id IN ({{.IDs}})
Задумка прикольная, но шаблонизатор не самая быстрая вешь

2024-07-07 19:12 UTC, Bazys commented on internal/app/httpserver/shorten/delete_short_urls.go
> +	if !isCorrectHeaderContentType {
```suggestion
	if !r.checkHeaderContentType(headerContentType) {
```

точно нужна лишняя переменная?

2024-07-07 19:12 UTC, Bazys commented on internal/app/httpserver/shorten/delete_short_urls.go
> +		r.urlUseCase.DeleteShortURLs(ctx, &req, ctx.GetString("user_id"))
хорошая задумка, но может случиться так, что контектс от джина будет с короким таймаутом и стор не успеет все удалить.
Плюс а вдруг ошибку вернули при удалении, как проверишь?
Щас норм, потом, как по теории дойдешь до errgroup - заменить

2024-07-07 19:12 UTC, Bazys commented on internal/app/httpserver/url/get_short_url.go
> +		} else if errors.As(err, &usecaseerrors.URLNotFound{}) {
ты же помнишь что каскад esle & return всегда можно упростить для простоты последующего чтения кода.

2024-07-07 19:12 UTC, Bazys commented on internal/app/memorystorage/url_repository.go
>  	"shorturl/internal/app/memorystorage/models"
правильная сортирвка импротов выглядит так:
1. stdlioib
2. внешние пакеты
3. твои пакеты
полдключи goimports или даже gofumpt на сохранение или на гит-хук при коммите и не надо будет каждый раз настраивать в ИДЕ

2024-07-07 19:12 UTC, Bazys commented on internal/app/pgstorage/url_repository.go
> +func (ur *URLRepository) DeleteShortURLs(ctx context.Context, urls *[]string, userID string) error {
*[]string - ссылка на слайс это масло масляное. Слайс сам по себе является ссылочным типом

2024-07-07 19:12 UTC, Bazys commented on internal/app/shortenerprovider/delete_urls.go
> +	urls *[]string,
а если ты делаешь ради того что бы не возвращать его из функции  - так это вообще антипаттерн (это просто поворчать)

2024-07-07 19:12 UTC, Bazys commented on internal/app/shortenerprovider/delete_urls.go
> +	if err != nil {
```suggestion
	if rows.Err() != nil {
```
опять, уверен что нужна эта переменная?

2024-07-07 19:12 UTC, Bazys commented on internal/app/usecase/url/errors/errors.go
> +type URLNotFound struct {
такая ошибка именуется в стиле `XxxError`

https://go.dev/wiki/Errors#naming

2024-07-07 19:12 UTC, Bazys commented on internal/app/validator/shorten_delete_short_urls.go
> +	var checks []validate.Validator
Преаллоцируй слайс. Тебе известен его будущий размер. как то так:
```go
checks := make([]validate.Validator, 0, len(*data))
```
Таки образом повышаем производительность Go-приложения за счет минимизации динамического выделения памяти во время выполнения. Предварительное аллоцирование слайсов в Go может значительно сократить накладные расходы на увеличение слайса по мере добавления элементов, что предполагает выделение новой памяти и копирование существующих элементов в новое пространство памяти.
В Go, когда вы заранее знаете количество элементов, которые будет вмещать слайс, вы можете использовать функцию `make`, чтобы указать его начальную длину и объем. Такая практика особенно полезна для слайсов, размер которых увеличивается по мере выполнения программы, поскольку избавляет Go от необходимости автоматически изменять размер слайса каждый раз, когда в него добавляется элемент после превышения его емкости.
Предварительное аллокация выгодна для производительности, особенно в сценариях с большими массивами данных или высокопроизводительными задачами, потому что она уменьшает количество выделений памяти и связанные с этим затраты на управление памятью, например сборку мусора.
Для более подробного тзучения оптимизации производительности кода Go и управления памятью, включая эффективное использование срезов и функции `make`, посмотри на таких ресурсам, как:
1. [The Impact of Preallocating Slice Memory in Golang (Continued)](https://oilbeater.com/en/2024/03/04/golang-slice-performance-cont/)
2. [Optimize by pre-allocating slice](https://www.programming-books.io/essential/go/optimize-by-pre-allocating-slice-ee6501b596c9446da8b82e4ed35454a6)

2024-07-13 12:51 UTC, Froctnow commented on internal/app/client/pg/queries/shortener.sql
> +WHERE id IN ({{.IDs}})
Уже обсуждали с тобой в другом MR, что я не хочу пользоваться ORM, а только чистый SQL, отсюда это подходящий вариант. На 4к RPS не вызывает каких-то нагрузок на ЦПУ/память, так что вполне пойдет.

2024-07-13 12:53 UTC, Froctnow commented on internal/app/httpserver/shorten/delete_short_urls.go
> +	if !isCorrectHeaderContentType {
Это делает код более читаемым. Если кажется, что лишняя память берется под это, могу убрать

2024-07-13 12:55 UTC, Froctnow commented on internal/app/httpserver/shorten/delete_short_urls.go
> +		r.urlUseCase.DeleteShortURLs(ctx, &req, ctx.GetString("user_id"))
Так в задаче не сказано что какие-то ошибки надо обрабатывать от этой конструкции. Отсюда я и подумал, что можно пустить в параллель и не обращать внимание. Если бы было условие с обработкой ошибок и какой-то логикой поверх (вывод в панель результатов, например), я бы добавил errgroup

2024-07-13 13:00 UTC, Froctnow commented on internal/app/httpserver/url/get_short_url.go
> +		} else if errors.As(err, &usecaseerrors.URLNotFound{}) {
Не очень понял как тут упростить, но попробовал чуть поправить, узнав, что в As с err=nil вернет false

2024-07-13 13:06 UTC, Froctnow commented on internal/app/pgstorage/url_repository.go
> +func (ur *URLRepository) DeleteShortURLs(ctx context.Context, urls *[]string, userID string) error {
Вот как. Думал все передается в Go по значению.

Everything in Go is passed by value, slices too. But a slice value is a header, describing a contiguous section of a backing array, and a slice value only contains a pointer to the array where the elements are actually stored. The slice value does not include its elements (unlike arrays).

Собственно ответ от Гугла понятен

2024-07-13 13:12 UTC, Froctnow commented on internal/app/shortenerprovider/delete_urls.go
> +	if err != nil {
Да, потому что тебе два раза надо делать rows.Err() тогда. Выглядит очень некрасиво

```
	err = rows.Err()
	if err != nil {
		return models.URLID{}, fmt.Errorf("can't execute GetURL: %w", err)
	}
```

```
	if rows.Err() != nil {
		return models.URLID{}, fmt.Errorf("can't execute GetURL: %w", rows.Err())
	}
```

2024-07-13 13:14 UTC, Froctnow commented on internal/app/validator/shorten_delete_short_urls.go
> +	var checks []validate.Validator
Это база, просто пропустил чет тут

2024-07-14 11:15 UTC, Bazys approved these changes

2024-07-14 13:29 UTC, merged