Iter9
Froctnow/shorturl pull request #9
Opened 2024-03-30 18:19 UTC by Froctnow

2024-04-09 21:20 UTC, Bazys requested changes
1. подключи `goimports` или даже `gofumpt` к своему проекту. Импорты точно должны быть отсортированы. Либо настрой IDE на форматирование одним из этих форматеров при сохранение, либо используй гит хук на соммит.
2. Надо бы пересмотреть подход к использованию `provider.IStorageProvider`
Посчмотри в сторону `Dependency Injection`. В го утиная типизация и нет необходимости явно указывать какому интерфейсу должна удовлетворять структура. Это твой сервер ожидает интерфейс, а структура просто удовлетворяет этому интерфейсу. И конструктор, возвращает именно структуру.
Почитай для начала вот [здесь](https://github.com/evrone/go-clean-template?tab=readme-ov-file#dependency-injection) . Там же есть про чистую архитектуру и ссылки для продолжения изучениия.

2024-04-09 21:20 UTC, Bazys commented on internal/app/log/console.go
> +func formatConsoleExtrasWithObscure(sensitiveFields []string, value interface{}) []byte {
зачем эта функция?

2024-04-09 21:20 UTC, Bazys commented on internal/app/httpserver/shorten/router.go
> +type ShortenRouter interface {
наружу это точит как `shorten.ShortenRouter` - подумай над неймингом.

1. **Общие правила именования пакетов**

- **Только строчные буквы:** Имена пакетов должны быть написаны строчными буквами. Избегайте использования подчеркивания или смешанных прописных букв. Например, используйте `net/http` вместо `Net/HTTP` или `net_http`.

- **Короткие и лаконичные:** Имена должны быть короткими и лаконичными. Длинные имена не добавляют ценности и неудобны в использовании.

- **Никаких множественных чисел:** Как правило, предпочитайте форму единственного числа. Например, используйте `package byte` вместо `package bytes`.

- **Описательные:** Выбирайте имена, которые четко описывают их функциональность. Например, `compress` для пакета, который занимается сжатием.

- **Избегайте совпадений:** Будьте осторожны и не называйте пакет так же, как обычные типы или переменные Go.

2. **Избегание распространенных ошибок**

- **Неописательные имена:** Избегайте расплывчатых имен типа `utils` или `helpers`. Они не передают назначение пакета.
- **Слишком общие или широкие:** Такие названия, как `data` или `api`, слишком расплывчаты. Уточните функциональность пакета.

3. **Иерархическое именование**
	При создании большого проекта вы можете создавать пакеты в иерархии. Однако Go не рекомендует создавать глубоко вложенные структуры пакетов. Хорошее правило - иметь структуру, которая отражает область применения модуля, а не структуру вашей команды или организации.

	Например, `github.com/myusername/projectname/auth` для модуля аутентификации в проекте.

4. **Ссылки для дальнейшего изучения**

Чтобы лучше усвоить материал, см. следующие ресурсы:
- **Блог Go:** В частности, пост под названием "Имена пакетов" предлагает ценные сведения ([blog.golang.org/package-names](https://blog.golang.org/package-names)).
- **Effective Go:** Этот раздел официальной документации Go содержит рекомендации по написанию понятного, идиоматичного кода Go, включая именование пакетов ([golang.org/doc/effective_go.html#package-names](https://golang.org/doc/effective_go.html#package-names)).
- **Комментарии к обзору Go-кода:** Это коллекция распространенных комментариев, сделанных во время обзоров Go-кода, которые могут быть полезны для понимания лучших практик ([CodeReviewComments](https://go.dev/wiki/CodeReviewComments#package-names)).
- [Go Style Decisions](https://google.github.io/styleguide/go/decisions#variable-names)

2024-04-09 21:20 UTC, Bazys commented on internal/app/log/log.go
> +type LogClient interface {
тоже нейминг

2024-04-13 06:26 UTC, Froctnow commented on internal/app/log/console.go
> +func formatConsoleExtrasWithObscure(sensitiveFields []string, value interface{}) []byte {
Действительно лишняя

2024-04-13 06:26 UTC, Froctnow commented on internal/app/httpserver/shorten/router.go
> +type ShortenRouter interface {
Да, затупил, надо было как с UseCase называть все, дал именование Router просто

2024-04-13 06:29 UTC, Froctnow commented on internal/app/log/log.go
> +type LogClient interface {
Я перенес это в пакет, как будто у нас микросервисы и мы бы тащили его с гитхаба. И там я оставил имя LogClient, а пакет logger, мне так кажется вполне логичным. Если же тебе кажется, что тут надо назвать Client без Log, то могу переименовать.

2024-05-19 08:32 UTC, merged